#!/bin/bash

#
# Script checks for mdraid health, and reports state of array.
#

# severity, depended on RAID state
OK=0
WARN=1
ERROR=2

# if no md name is given, exit wtih WARN + 1
[ -z $1 ] && echo $OK && exit 1

# if there is no such block device, exit with WARN + 1
[ ! -b /dev/$1 ] && echo $OK && exit 1

sudo /sbin/mdadm --detail /dev/$1 | grep '  State' | egrep -q ' (active|clean)'
RAIDOK=$?
sudo /sbin/mdadm --detail /dev/$1 | grep '  State' | egrep -q '(resyncing|recovering|degraded)'
RAIDWARN=$?

# if state is not active/clean, we're in trouble
if [ $RAIDOK -eq 0 ]; then
  # check if we're resilvering/recovering/degraded
  if [ $RAIDWARN -eq 0 ]; then
    # if we're resyncing, we can be in check state, which is weekly schedule
    SYNC_ACTION="$(cat /sys/block/$1/md/sync_action)"
    [ $SYNC_ACTION == "check" ] && echo $OK || echo $WARN
  else
    echo $OK
  fi
else
  echo $ERROR
fi

exit 0
